name: GNAT 10 on Ubuntu 20.04

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat-10 gprbuild

    - name: Build Audio Library
      run: gprbuild -P audio_base.gpr
