name: GNAT 7 on Ubuntu 18.04

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install gnat-7 gprbuild

    - name: Build Audio Library
      run: gprbuild -P audio_base.gpr
